site:
  title: opennms.py
content:
  sources:
    - url: .
      branches: HEAD
      start_path: docs
ui:
  bundle:
    url: https://github.com/opennms-forge/antora-ui-opennms/releases/download/v3.1.0/ui-bundle.zip
  supplemental_files:
    - path: ui.yml
      contents: |
        static_files:
        - .nojekyll
        - index.html
    - path: .nojekyll
    - path: index.html
      contents: |
        <html><head><meta http-equiv="refresh" content="0; url='opennms.py/0.0.12/index.html'" /></head></html>
asciidoc:
  attributes:
    experimental: true
output:
  clean: true
  dir: ./public
  destinations:
    - provider: fs
    - provider: archive
